sudo: required
language: generic 

services:
  - docker: 

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t arnav30/microblog -f Dockerfile.dev .

script:
  - docker run -e CI=true arnav30/microblog tests.py &

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master