sudo: required
language: generic 

services:
  - docker: 

before_install:
  - docker build -t arnav30/microblog:4.0 -f Dockerfile.dev .

script:
  - docker run -e CI=true arnav30/microblog:4.0 tests.py