version: '3'
services:
    web:
      build: .
      ports:
      - 8000:5000

      environment:
        SECRET_KEY: my-secret-key
        DATABASE_URL: mysql+pymysql://microblog:pw@dbserver/microblog
      links:
      - mysql:dbserver

    mysql:
      image: mysql/mysql-server:5.6
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: random
        MYSQL_DATABASE: microblog
        MYSQL_USER: microblog
        MYSQL_PASSWORD: pw